### ISSUE TITLE
Question: Using Camel LSP with Spring Boot

### ISSUE THREAD

**Issue by assimbly** [camel-tooling/camel-language-server#760]
I have a Spring Boot (Backend) / Angular (Frontend) application. In the frontend there is a codemirror editor to edit Camel routes. Now I like to add support for Camel code completion and I checked the code-mirror example:

https://github.com/camel-tooling/camel-lsp-client-codemirror

In the example the LSP seems to be running as an independent server. 

https://mvnrepository.com/artifact/com.github.camel-tooling/camel-lsp-server

Is is it also possible to embed the Camel LSP directly into my Spring Boot backend? If so, do I need to configurate/code something to enable it (especially websockets)? Or can I just add Camel LSP as an dependency?

**Comment by apupier** [comment]
> Is is it also possible to embed the Camel LSP directly into my Spring Boot backend? If so, do I need to configurate/code something to enable it (especially websockets)? Or can I just add Camel LSP as an dependency?

I never tried it myself but in theory yes:
- I think you will need to write some glue code so that when Spring Boot is starting, it is calling this kind of code https://github.com/camel-tooling/camel-language-server/blob/fdf82f47cc1ccb4e32d5afa1bbd4e4c24f87c164/src/main/java/com/github/cameltooling/lsp/internal/Runner.java#L59-L63
- For CodeMirror, you will need to configure with a Websocket communication.

it might be possible to configure the Camel language Server with Spring Boot annotation so that no glue code is required. In this case, if you provide a Pull request, I will be happy to review it.

**Comment by skin27** [comment]
Thanks, I think there are multiple approaches:

- Use either some glue code or use Spring Websocket Configuration (like I have here https://github.com/assimbly/gateway/blob/master/src/main/java/org/assimbly/gateway/config/WebsocketConfiguration.java)

- And then need to adjust the ports etc in the frontend adapter config. 

I already managed to communicate from CodeMirror to a standalone LSP using the code mirror example. There the websocket communication was working, but the editor didn't show any hints. This is probably because I use ngx-codemirror which doesn't support hints (https://github.com/scttcper/ngx-codemirror/issues/235).

I leave it for now because of:

1) hints not working in nxg-codemirror
2) lsp-editor-adapter package doesn't seem to get updated (it works though).
3) Embedding the LSP seems to be pretty large (around 80mb), because it's batteries included.  It contains all languages/catalogs (currently I only need a part of it). Or are there also stripped down versions?

Probably will experiment with it later on, because the functionality of LSP is kinda cool. My question is answered so you can close this ticket.

**Comment by skin27** [comment]
On point 3. For embedding it would be good to have modularized version (just like camel) with a core lsp and then add suppor for languages or support when needed.
